accel_fps: 100
accel_info_qos: DEFAULT
accel_qos: SENSOR_DATA
align_depth.enable: true
align_depth.frames_queue_size: 16
angular_velocity_cov: 0.01
base_frame_id: link
camera_name: mel
clip_distance: -1.0
color_info_qos: DEFAULT
color_qos: SYSTEM_DEFAULT
colorizer.color_scheme: 0
colorizer.enable: false
colorizer.frames_queue_size: 16
colorizer.histogram_equalization_enabled: true
colorizer.max_distance: 6.0
colorizer.min_distance: 0.0
colorizer.stream_filter: 1
colorizer.stream_format_filter: 1
colorizer.stream_index_filter: -1
colorizer.visual_preset: 0
decimation_filter.enable: false
decimation_filter.filter_magnitude: 2
decimation_filter.frames_queue_size: 16
decimation_filter.stream_filter: 1
decimation_filter.stream_format_filter: 1
decimation_filter.stream_index_filter: -1
depth_info_qos: DEFAULT
depth_module.auto_exposure_roi.bottom: 479
depth_module.auto_exposure_roi.left: 0
depth_module.auto_exposure_roi.right: 847
depth_module.auto_exposure_roi.top: 0
depth_module.emitter_always_on: false
depth_module.emitter_enabled: 1
depth_module.emitter_on_off: false
depth_module.enable_auto_exposure: false
depth_module.error_polling_enabled: true
depth_module.exposure: 33000
depth_module.frames_queue_size: 16
depth_module.gain: 16
depth_module.global_time_enabled: true
depth_module.hdr_enabled: false
depth_module.inter_cam_sync_mode: 0
depth_module.laser_power: 150.0
depth_module.output_trigger_enabled: false
depth_module.profile: 848x480x30
depth_module.sequence_id: 0
depth_module.sequence_name: 0
depth_module.sequence_size: 2
depth_module.thermal_compensation: true
depth_module.visual_preset: 0
depth_qos: SYSTEM_DEFAULT
device_type: ''
diagnostics_period: 0.0
disparity_filter.enable: false
disparity_to_depth.enable: false
enable_accel: false
enable_color: true
enable_depth: true
enable_gyro: false
enable_infra: false
enable_infra1: false
enable_infra2: false
enable_sync: false
filter_by_sequence_id.enable: false
filter_by_sequence_id.frames_queue_size: 16
filter_by_sequence_id.sequence_id: 1
gyro_fps: 200
gyro_info_qos: DEFAULT
gyro_qos: SENSOR_DATA
hdr_merge.enable: false
hdr_merge.frames_queue_size: 16
hold_back_imu_for_frames: false
hole_filling_filter.enable: false
hole_filling_filter.frames_queue_size: 16
hole_filling_filter.holes_fill: 1
hole_filling_filter.stream_filter: 1
hole_filling_filter.stream_format_filter: 1
hole_filling_filter.stream_index_filter: -1
infra1_info_qos: DEFAULT
infra1_qos: SYSTEM_DEFAULT
infra2_info_qos: DEFAULT
infra2_qos: SYSTEM_DEFAULT
infra_info_qos: DEFAULT
infra_qos: SYSTEM_DEFAULT
initial_reset: false
json_file_path: ''
linear_accel_cov: 0.01
motion_module.enable_motion_correction: true
motion_module.frames_queue_size: 16
motion_module.global_time_enabled: true
pointcloud.allow_no_texture_points: false
pointcloud.enable: false
pointcloud.filter_magnitude: 2
pointcloud.frames_queue_size: 16
pointcloud.ordered_pc: false
pointcloud.pointcloud_qos: DEFAULT
pointcloud.stream_filter: 0
pointcloud.stream_format_filter: 0
pointcloud.stream_index_filter: -1
publish_odom_tf: true
publish_tf: true
reconnect_timeout: 6.0
rgb_camera.auto_exposure_priority: false
rgb_camera.auto_exposure_roi.bottom: 719
rgb_camera.auto_exposure_roi.left: 0
rgb_camera.auto_exposure_roi.right: 1279
rgb_camera.auto_exposure_roi.top: 0
rgb_camera.backlight_compensation: false
rgb_camera.brightness: 0
rgb_camera.contrast: 50
rgb_camera.enable_auto_exposure: false
rgb_camera.enable_auto_white_balance: false
rgb_camera.exposure: 100
rgb_camera.frames_queue_size: 16
rgb_camera.gain: 64
rgb_camera.gamma: 300
rgb_camera.global_time_enabled: true
rgb_camera.hue: 0
rgb_camera.power_line_frequency: null
rgb_camera.profile: 1280x720x30
rgb_camera.saturation: 64
rgb_camera.sharpness: 50
rgb_camera.white_balance: 3330.0
rosbag_filename: ''
serial_no: '239222303414'
spatial_filter.enable: false
spatial_filter.filter_magnitude: 2
spatial_filter.filter_smooth_alpha: 0.5
spatial_filter.filter_smooth_delta: 20
spatial_filter.frames_queue_size: 16
spatial_filter.holes_fill: 0
spatial_filter.stream_filter: 1
spatial_filter.stream_format_filter: 1
spatial_filter.stream_index_filter: -1
temporal_filter.enable: false
temporal_filter.filter_smooth_alpha: 0.4000000059604645
temporal_filter.filter_smooth_delta: 20
temporal_filter.frames_queue_size: 16
temporal_filter.holes_fill: 3
temporal_filter.stream_filter: 1
temporal_filter.stream_format_filter: 1
temporal_filter.stream_index_filter: -1
tf_publish_rate: 0.0
unite_imu_method: 0
usb_port_id: ''
use_sim_time: false
wait_for_device_timeout: -1.0
